export { default as Header_Style } from './Header/header'
export { default as Sidebar_Style } from './Sidebar/sidebar_style'
export { default as Notifications_style } from './Header/notifications'
export { default as AmbulanceTable_style } from './AmbulanceUse/AmbulanceTable'

export { default as AmbulanceUse_style } from './AmbulanceUse/AmbulanceUse'
export { default as Dashborad_style } from './Dashborad/Dashborad'
export { default as ButtonStatus_style } from './Maps/ButtonStatus'
export { default as CurrentMap_style } from './Maps/CurrentMap'
export { default as MapsInfo_style } from './Maps/MapsInfo'
export { default as PeopleRequest_style } from './ReqList/PeopleRequest'
export { default as SendAmbulance_style } from './ReqList/SendAmbulance'
export { default as UserTable_style } from './ReqList/UserTable'